### ISSUE TITLE
Images not loading.

### ISSUE THREAD

**Issue by Labohkip81** [WhyNotHugo/django-renderpdf#5]
```
  {% for ticket in ticket.order.orderitems.all %}
            <div>
              <img
                height="120px" width="200px" style="float: right;"
                src="{{ ticket.item.image_original.url }}"
                alt="{{ ticket.item.title }}"
              />
            </div>
            {% endfor %}
````
The above is not rendered to the generated pdf file.

**Comment by WhyNotHugo** [comment]
What exactly is the value of `ticket.item.image_original.url`? (You can add it plainly into the PDF to figure that out quickly).

**Comment by Labohkip81** [comment]
Well its a jpg image . ```/media/media/isiolo.jpg```
I cant add it plainly since they are user uploaded images. For this case used to generate tickets for their event.

**Comment by WhyNotHugo** [comment]
Hmm.. You're serving images with Django (or they're in the same domain/port as the app), right? I don't think I'd ever thought of that scenario.

Are you also serving staticfiles via django?

If both my assumptions are true, the issue is probably [here](https://github.com/WhyNotHugo/django-renderpdf/blob/master/django_renderpdf/helpers.py#L26), where static files are loaded locally, rather than make a network call to wherever they're being served (which generally impacts performance in production).

Making your URLs absolute should work. Lemme see if I can think of an easy/clean way to work around this otherwise.

**Comment by WhyNotHugo** [comment]
Actually, surrounding the `if` part in a try/except might just work. Are you seeing any errors  getting logged when generating the PDF?

**Comment by Labohkip81** [comment]
Yes i'm serving my static files using Django,
I'll come up with a small project to replicate the same once i wake up.

**Comment by WhyNotHugo** [comment]
So I've recently gotten two more emails for a few similar scenarios where this occurs.

Seems like how I'm handling media and static files doesn't work for everyone. The breakage is when files (either static or media) are served via relative URLs.

I don't think I've any services where that's the case, so I haven't come across this. I'll try to address this during this week, but have to add lots of tests for the variety of scenarios that might occurs depending on Django settings.

**Comment by Symonss** [comment]
I'm getting this problem too,

**Comment by Symonss** [comment]
My current fix is to get the current domain then concatenate with the absolute url

**Comment by dannywillems** [comment]
I would suggest to reopen this one @WhyNotHugo. The library does not support `ImageField` at the moment. It would be nice if it was.

**Comment by dannywillems** [comment]
I'm getting:
```
ERROR:weasyprint:Failed to load image at '/media/dir/file.jpg': AttributeError: type object 'HttpRequest' has no attribute 'META'
```
